In [16]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model

In [18]:
sales = pd.read_csv('home_data.csv')

In [19]:
sales.head()

id             date   price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900         3       1.00         1180   
1  6414100192  20141209T000000  538000         3       2.25         2570   
2  5631500400  20150225T000000  180000         2       1.00          770   
3  2487200875  20141209T000000  604000         4       3.00         1960   
4  1954400510  20150218T000000  510000         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650       1           0     0     ...          7        1180   
1      7242       2           0     0     ...          7        2170   
2     10000       1           0     0     ...          6         770   
3      5000       1           0     0     ...          7        1050   
4      8080       1           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [21]:
sales_X = sales['sqft_living']

In [48]:
x = []
for i in sales_X:
    x.append(i)
xarray = np.array(x)
xarray

array([1180, 2570,  770, ..., 1020, 1600, 1020])

In [68]:
sales_X_train = xarray[:-20]
sales_X_train.reshape(len(sales_X_train),1)

array([[1180],
       [2570],
       [ 770],
       ..., 
       [4910],
       [2770],
       [1190]])

In [53]:
sales_X_test = xarray[-20:]

In [54]:
sales_X_test

array([4170, 2500, 1530, 3600, 3410, 3118, 3990, 4470, 1425, 1500, 2270,
       1490, 2520, 3510, 1310, 1530, 2310, 1020, 1600, 1020])

In [33]:
sales_Y = sales['price']

In [55]:
y = []
for m in sales_Y:
    y.append(m)
yarray = np.array(y)
yarray

array([221900, 538000, 180000, ..., 402101, 400000, 325000])

In [58]:
sales_y_train = yarray[:-20]
sales_y_test = yarray[-20:]

In [66]:
sales_y_train.reshape(len(sales_y_train),1)

array([[ 221900],
       [ 538000],
       [ 180000],
       ..., 
       [1222500],
       [ 572000],
       [ 475000]])

In [59]:
regr = linear_model.LinearRegression()

In [70]:
regr.fit(sales_X_train.reshape(len(sales_X_train),1), sales_y_train.reshape(len(sales_y_train),1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [71]:
print("Coefficients: \n", regr.coef_)

('Coefficients: \n', array([[ 280.6363448]]))


In [ ]:
print("Residual sum of squares: %.2f"
      % np.mean((regr.predict(sales_X_test.reshape(len(sales_X_test),1)) - sales_y_test.reshape(len(sales_y_test),1)) ** 2))

In [ ]:
print('Variance score: %.2f' % regr.score(sales_X_test.reshape(len(sales_X_test),1), sales_y_test.reshape(len(sales_y_test),1)))

In [ ]:
plt.scatter(sales_X_test.reshape(len(sales_X_test),1), sales_y_test.reshape(len(sales_y_test),1),  color='black')
plt.plot(sales_X_test.reshape(len(sales_X_test),1), sales_y_test.reshape(len(sales_y_test),1), color='blue',
         linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()